# References {.unnumbered}

::: {#refs}
:::

Aiello, M., Vezzoli, R. and Gianinetto, M. (2019) \'Object-based image analysis approach for vessel detection on optical and radar images\', *Journal of Applied Remote Sensing*, 13, p. 14502. Available at: <https://doi.org/10.1117/1.JRS.13.014502>.

Al-Bilbisi, H. (2019) \'Spatial Monitoring of Urban Expansion Using Satellite Remote Sensing Images: A Case Study of Amman City, Jordan\', *Sustainability*, 11(8), p. 2260. Available at: <https://doi.org/10.3390/su11082260>.

Li, D. *et al.* (2022) \'Modeling the relationships between historical redlining, urban heat, and heat-related emergency department visits: An examination of 11 Texas cities\', *Environment and Planning B: Urban Analytics and City Science*, 49(3), pp. 933--952. Available at: <https://doi.org/10.1177/23998083211039854>.

Liu, C. *et al.* (2016) \'A land use regression application into assessing spatial variation of intra-urban fine particulate matter (PM2.5) and nitrogen dioxide (NO2) concentrations in City of Shanghai, China\', *Science of The Total Environment*, 565, pp. 607--615. Available at: <https://doi.org/10.1016/j.scitotenv.2016.03.189>.

Rundquist, D.C. *et al.* (1996) \'Remote measurement of algal chlorophyll in surface waters: the case for the first derivative of reflectance near 690 nm\', *Photogrammetric Engineering and Remote Sensing*, 62(2), pp. 195--200.

SCHULTZ, J. (1979) \'APPLICATIONS OF LANDSAT SA℡LITE IMAGERY FOR RESOURCE INVENTORY AND EVALUATION IN DEVELOPING COUNTRIES\', *GeoJournal*, 3(1), pp. 53--62.

State of Palestine Ministry of Local Government (2021) \'Implementation of the New Urban Agenda: National Report for the State of Palestine\'. Available at: <https://www.urbanagendaplatform.org/sites/default/files/2022-01/Palestine%20NUA%20National%20Report_English.pdf>.

*The New Urban Agenda* (no date) *Habitat III*. Available at: <https://habitat3.org/the-new-urban-agenda/> (Accessed: 18 March 2023).

Webber, F. *et al.* (2014) \'Borders, deaths and resistance\', *Statewatch Journal*, 23(3/4). Available at: <https://www.borderline-europe.de/sites/default/files/background/statewatch-journal-vol23n34.pdf#page=9>.

Zhang, Ying *et al.* (2021) \'Satellite remote sensing of atmospheric particulate matter mass concentration: Advances, challenges, and perspectives\', *Fundamental Research*, 1(3), pp. 240--258. Available at: <https://doi.org/10.1016/j.fmre.2021.04.007>.
