# Week 1: Getting Started with Remote Sensing

## Summary
SORRY I AM WRITING THEM IN A DIFFERENT FILE AND HAVEN'T ADDED THEM INTO HERE YET!!

### Sensors
Active vs Passive

### Data
- different types of resolutions
1. spatial
- size of raster cell (ex: 10m. RBG are all 10m bands)
2. spectral
- electromagnetic spectrum
- # of bands (ex: RGB is 3 bands)
3. radiometric
- bits
- granularity of energy
4. temporal
- time of sensor revisiting

*Can downscale or upscale bands to convert them to diff spatial resolution so we can use more of the spectral data. downscaling is intensive but upscaling (aka resampling) can be done with knn or majority rule. 

bands
- [insert bands image]

Color Composites
(1) True Colour Composite (B1=Blue, B2=Green, B3=Red) [insert image]
(2) False Color Composite (B8, B4, B3) - Plants reflect near-infrared and green light whilst absorbing red.
(3) Atmospheric Penetration Composite - B12, B11, B8A with no visible bands to penetrate atmospheric particles. Vegetation = blue, urban area = white, gray cyan or purple.
(4) Short-wave Infrared Composite (B12, B8A and B4) - shows vegetation in green, the darker the greener the denser it is and brown shows built up or bare soil
...and there are more 

### Sentinal Data 

Spectral Feature Space - Wizard/Tasseled Cap
- x axis (brightness): B4 (red) - vegetation absorbs 
- y axis (greenness): B8 (near infrared reflectance) - vegetation reflects
[insert plot]

Tasseled Cap Function: A way of transforming original data to new data with reduced dimensionalirt (using PCA - reducing dimensions while maximising variance).
Brightness, associated with spectral bands that show bare soil, man made surfaces or bight materials
Greenness, associated with green vegetation
Wetness, associated with moisture

### Landsat Data

## Applications

## Reflection
